### ALL
POST http://localhost:8101/all
Content-Type: application/json

{
    "order": {
        "orderId": "yi7o-2421-dad",
        "status": "Order Placed"
    },
    "media": {
        "mediaId": "yi7o-2421-dad",
        "status": "Media Placed"
    }
}